# starts cassandra db and jupyter lab
version: '3.1'

services:

  db:
    image: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  jupiter:
    image: jupyter/datascience-notebook
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      DB_HOST: 'db'
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888

